language: python
sudo: required
python:
    - '3.6'
    - '2.7'
install:
    - pip install 'pytest'
    - pip install 'numpy'
    - pip install 'librosa==0.5'
    - pip install 'matplotlib'
    - pip install 'requests'
    - pip install 'bs4'
    - pip install 'tqdm'
    - pip install 'imageio'

cache: pip
script:
    - python setup.py install
    - pytest tests/