language: python
sudo: required
python:
    - '3.6'
    - '2.7'
before_install:
  - sudo apt-get install -y sox

install:
    - pip install 'pytest'
    - pip install 'numpy'
    - pip install 'librosa'
    - pip install 'matplotlib'
    - pip install 'requests'
    - pip install 'bs4'
    - pip install 'tqdm'
    - pip install 'imageio'

cache: pip
script:
    - python setup.py install
    - pytest tests/

deploy:
  provider: pypi
  user: $PYPI_USERNAME
  password: $PYPI_PASSWORD
  skip_existing: true
  on:
    tags: true